Release
grafchitaru/summarize pull request #1
Opened 2024-02-27 06:02 UTC by grafchitaru

2024-03-03 08:33 UTC, bambruysk requested changes
Неплохо, продолжаем,

Следует уделить внимание контекстам

2024-03-03 08:33 UTC, bambruysk commented on internal/ai/gigachat/gigachat.go
> +	}
рекомендую исползовать https://github.com/go-resty/resty - более ясный и читаемый код
Здесь так же идет поход во внешний api без контекста, и программа может тут застрять

2024-03-03 08:33 UTC, bambruysk commented on internal/ai/gigachat/gigachat.go
> +	res, err := client.Do(req)
здесь снова поход без контекста и таймаута

2024-03-03 08:33 UTC, bambruysk commented on internal/ai/gigachat/gigachat.go
> +
а это не тоже самое что 
```
tokens := len(text)/tokenLength 
if len(text) % /tokenLength != 0 {
   tokens++
 }
```
Или 
`tokens :=  int(math.Ceil(float64(len(text))/float64(tokenLength)))`

2024-03-03 08:33 UTC, bambruysk commented on internal/config/config.go
> +type HandlerContext struct {
почему этот контекст в пакете конфигурации? И почему он собственно не является контекстом?

2024-03-03 08:33 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +	}
удобнее делать ошибки возвращаемые разными 

return fmt.Errorf("%s begin tx: %w", op, err)
return fmt.Errorf("%s exec: %w", op, err)

И тд. Тогда понятно из какой строчки возвращается.  Pgx возвращает подробные ошибки, но бывает когда кидается что-то типа EOF,  и думаешь, откуда ты такое,

2024-03-03 08:33 UTC, bambruysk commented on internal/storage/postgresql/postgresql.go
> +	return id, nil
здесь везде идет поход в базу без контекста с таймаутом или отменой, Очень нестабильное решение, лучше всегда ходить во внешний сервис с контекстом

2024-03-03 08:33 UTC, bambruysk commented on internal/handlers/login.go
> +func Login(ctx config.HandlerContext, res http.ResponseWriter, req *http.Request) {
Контекст здесь не контекст, лучше сделать это методом структуры. типа config.HandlerContext. Тогда эта функция будет подходить под тип http.Handle - и будет удобнее их использовать

Контексты -  это набор данных относящихся к данному процессу ( не в смысле ОС а в более широком смысле) 
То есть есть например контекст процесса обработки запроса, есть всякие requestID, userID таймаут исполнения, механики исполнения  и отмены и так далее.  
context.Context -  это интерфейс позволяющий запаковать это все в одну сущность, и передавать ее через аргументы вызываемых функций

2024-03-03 08:33 UTC, bambruysk commented on internal/handlers/summarize.go
> +	summarizeText, err := ctx.Ai.Send(text, ctx.Config.AiSummarizePrompt)
если ctx.Config.AiSummarizePrompt - не меняется то почему бы не сделать его полем структуры Ai - зачем передавать лишние аргументы? 

У нас вроде бы планировалось асинхронная реализация этой механики? - то есть отправляем текст на суммаризацию, потом по кускам суммируем, потом собираем из этого результат.

2024-03-03 08:33 UTC, bambruysk commented on internal/storage/repositories.go
> +}
Лучше бы копии этих структур вынести в отдельный пакет models -  непонятно почему  все должны знать про Storage

И я бы добавил таймстемпы UpdatedAt в них

2024-03-03 08:33 UTC, bambruysk commented on internal/storage/repositories.go
> +	CreateSummarize(id string, user_id string, text string, status string, tokens int) error
слишком много аргументов, пользоваться такой трудно. Лучше сделать структуру запроса, или использовать Summarize

2024-03-03 15:50 UTC, grafchitaru commented on internal/storage/postgresql/postgresql.go
> +	}
Добавил

2024-03-03 16:04 UTC, grafchitaru commented on internal/storage/postgresql/postgresql.go
> +	return id, nil
Готово

2024-03-03 16:43 UTC, grafchitaru commented on internal/storage/repositories.go
> +}
Готово

2024-03-03 17:44 UTC, grafchitaru commented on internal/ai/gigachat/gigachat.go
> +	}
Готово

2024-03-03 17:44 UTC, grafchitaru commented on internal/ai/gigachat/gigachat.go
> +	res, err := client.Do(req)
Готово

2024-03-03 17:47 UTC, grafchitaru commented on internal/ai/gigachat/gigachat.go
> +
Да, действительно. Спасибо. Сделал

2024-03-04 05:14 UTC, grafchitaru commented on internal/storage/repositories.go
> +	CreateSummarize(id string, user_id string, text string, status string, tokens int) error
Сделал

2024-03-04 13:04 UTC, grafchitaru commented on internal/handlers/login.go
> +func Login(ctx config.HandlerContext, res http.ResponseWriter, req *http.Request) {
Готово

2024-03-04 13:04 UTC, grafchitaru commented on internal/config/config.go
> +type HandlerContext struct {
Готово

2024-03-04 13:07 UTC, grafchitaru commented on internal/handlers/summarize.go
> +	summarizeText, err := ctx.Ai.Send(text, ctx.Config.AiSummarizePrompt)
Смысл в том, чтобы быстро менять разные промпты и тестировать - какой лучше подойдет. Поэтому вынес это в конфиг.

2024-03-04 13:42 UTC, grafchitaru commented on internal/handlers/summarize.go
> +	summarizeText, err := ctx.Ai.Send(text, ctx.Config.AiSummarizePrompt)
Сделал отправку ассинхронной и поделенной на чанки

2024-03-04 20:34 UTC, bambruysk requested changes
Хорошо! Надо поправитьь горутины и норм. И еще продумать как их гресфульно завершать

2024-03-04 20:34 UTC, bambruysk commented on internal/handlers/context.go
> +type HandlerContext struct {
Все таки лучше избавиться от Context -  назвать Handlers

2024-03-04 20:34 UTC, bambruysk commented on internal/handlers/summarize.go
> +					http.Error(res, err.Error(), http.StatusBadRequest)
подозрительная строка -  тут пишем в res ,  но мы ж в другой горутине - хендлер то уже закончил работу. Значит ошибка потерялась на самом деле

2024-03-04 20:34 UTC, bambruysk commented on internal/handlers/summarize.go
> +		finalSummarizedText := fmt.Sprintf("%s", summarizedTexts)
строки тут большие вероятно, чтобы их склеивать лучше использовать stringsBuilder

2024-03-04 20:34 UTC, bambruysk commented on internal/handlers/summarize.go
> +				summarizedTexts = append(summarizedTexts, summarizedChunk)
а не страшно что они будут в рандомном порядке склеиваться? Может сохранить порядок как в чанках?

2024-03-04 20:34 UTC, bambruysk commented on internal/handlers/summarize.go
> +			http.Error(res, err.Error(), http.StatusBadRequest)
здесь нет смысла писать в ответ уже, тот поезд уже ушел - лучше в лог написать и в базу например

2024-03-04 20:34 UTC, bambruysk commented on internal/handlers/summarize.go
> +		err = ctx.Repos.UpdateSummarizeResult(summarizeID.String(), "Complete", finalSummarizedText)
надо бы механизм ретраев добавить кмк, хотя бы в тудушку

и еще хорошо бы эту горутину отнести в сервисный слой бизнес-логики

2024-03-05 11:47 UTC, grafchitaru commented on internal/handlers/context.go
> +type HandlerContext struct {
Готово

2024-03-05 11:47 UTC, grafchitaru commented on internal/handlers/summarize.go
> +					http.Error(res, err.Error(), http.StatusBadRequest)
Готово

2024-03-05 11:47 UTC, grafchitaru commented on internal/handlers/summarize.go
> +		finalSummarizedText := fmt.Sprintf("%s", summarizedTexts)
Готово

2024-03-05 11:47 UTC, grafchitaru commented on internal/handlers/summarize.go
> +				summarizedTexts = append(summarizedTexts, summarizedChunk)
Готово

2024-03-05 11:47 UTC, grafchitaru commented on internal/handlers/summarize.go
> +			http.Error(res, err.Error(), http.StatusBadRequest)
Готово

2024-03-05 11:47 UTC, grafchitaru commented on internal/handlers/summarize.go
> +		err = ctx.Repos.UpdateSummarizeResult(summarizeID.String(), "Complete", finalSummarizedText)
Готово

2024-03-08 07:30 UTC, bambruysk approved these changes
Неплохо. Замечания исправлены. Хочется увидеть это в работе)

2024-03-12 07:05 UTC, merged